import 'package:kipto/core/domain/models/fact.dart';
import 'package:kipto/core/domain/models/fact_value.dart';
import 'package:kipto/core/domain/models/item_action.dart';

final class AnalysisFact {
  const AnalysisFact({
    required this.key,
    required this.type,
    required this.value,
    required this.evidence,
    this.uncertainty,
  });
  final String key, type;
  final FactValue value;
  final FactEvidence evidence;
  final String? uncertainty;
}

final class AnalysisSuggestion {
  AnalysisSuggestion({
    required this.key,
    required this.kind,
    required this.title,
    required List<String> relatedFactKeys,
    required this.anchorFactKey,
    required List<String> needsUserInput,
    required this.reason,
  }) : relatedFactKeys = List.unmodifiable(relatedFactKeys),
       needsUserInput = List.unmodifiable(needsUserInput);
  final String key, title, reason;
  final ActionKind kind;
  final List<String> relatedFactKeys, needsUserInput;
  final String? anchorFactKey;
}

final class AnalysisOutput {
  AnalysisOutput._({
    required this.sourceRevision,
    required this.documentLabel,
    required this.title,
    required this.summary,
    required this.isPartial,
    required List<int> analyzedPages,
    required List<AnalysisFact> facts,
    required List<AnalysisSuggestion> suggestions,
    required List<String> warnings,
  }) : analyzedPages = List.unmodifiable(analyzedPages),
       facts = List.unmodifiable(facts),
       suggestions = List.unmodifiable(suggestions),
       warnings = List.unmodifiable(warnings);
  final int sourceRevision;
  final String documentLabel, title, summary;
  final bool isPartial;
  final List<int> analyzedPages;
  final List<AnalysisFact> facts;
  final List<AnalysisSuggestion> suggestions;
  final List<String> warnings;

  /// Evidence is checked against the actual supplied page, never another page
  /// or text generated by the model. Images remain visual references.
  factory AnalysisOutput.parse(
    Map<String, dynamic> json, {
    required int expectedRevision,
    required List<int> expectedPages,
    required bool expectedPartial,
    required bool imageInput,
    Map<int, String> textPages = const {},
  }) {
    requireKeys(json, {
      'schemaVersion',
      'sourceRevision',
      'documentLabel',
      'title',
      'summary',
      'coverage',
      'facts',
      'suggestions',
      'warnings',
    });
    if (json['schemaVersion'] != 1 ||
        json['sourceRevision'] != expectedRevision ||
        expectedRevision < 1) {
      throw const FormatException('Analysis revision mismatch');
    }
    final coverage = Map<String, dynamic>.from(json['coverage'] as Map);
    requireKeys(coverage, {'isPartial', 'analyzedPages'});
    final pages = (coverage['analyzedPages'] as List).cast<int>();
    if (pages.isEmpty ||
        pages.length > 10 ||
        pages.any((p) => p < 1) ||
        pages.toSet().length != pages.length ||
        pages.length != expectedPages.length ||
        !pages.toSet().containsAll(expectedPages) ||
        coverage['isPartial'] != expectedPartial) {
      throw const FormatException('Coverage mismatch');
    }
    final rawFacts = json['facts'] as List;
    final rawSuggestions = json['suggestions'] as List;
    final rawWarnings = json['warnings'] as List;
    if (rawFacts.length > 12 ||
        rawSuggestions.length > 6 ||
        rawWarnings.length > 8) {
      throw const FormatException('Analysis output limit exceeded');
    }
    final facts = <AnalysisFact>[];
    final keys = <String>{};
    for (final raw in rawFacts) {
      final f = Map<String, dynamic>.from(raw as Map);
      requireKeys(f, {
        'key',
        'type',
        'valueType',
        'value',
        'evidence',
        'uncertainty',
      });
      final key = boundedText(f['key'], 32);
      if (!keys.add(key)) throw const FormatException('Duplicate fact key');
      final e = Map<String, dynamic>.from(f['evidence'] as Map);
      requireKeys(e, {'page', 'quote'});
      final page = e['page'] as int?;
      final quote = e['quote'] as String?;
      if (page != null && !pages.contains(page)) {
        throw const FormatException('Evidence outside analyzed pages');
      }
      final verification = page == null
          ? EvidenceVerification.unverified
          : imageInput
          ? EvidenceVerification.visualReference
          : quote != null &&
                quote.isNotEmpty &&
                (textPages[page]?.contains(quote) ?? false)
          ? EvidenceVerification.textMatched
          : EvidenceVerification.unverified;
      facts.add(
        AnalysisFact(
          key: key,
          type: boundedText(f['type'], 100),
          value: FactValue.parse(
            f['valueType'] as String,
            Map<String, dynamic>.from(f['value'] as Map),
          ),
          evidence: FactEvidence(
            page: page,
            quote: quote,
            verification: verification,
          ),
          uncertainty: f['uncertainty'] == null
              ? null
              : boundedText(f['uncertainty'], 300),
        ),
      );
    }
    final suggestionKeys = <String>{};
    final suggestions = <AnalysisSuggestion>[];
    for (final raw in rawSuggestions) {
      final a = Map<String, dynamic>.from(raw as Map);
      requireKeys(a, {
        'key',
        'kind',
        'title',
        'relatedFactKeys',
        'anchorFactKey',
        'needsUserInput',
        'reason',
      });
      final key = boundedText(a['key'], 32);
      final related = (a['relatedFactKeys'] as List).cast<String>();
      final missing = (a['needsUserInput'] as List).cast<String>();
      final anchor = a['anchorFactKey'] as String?;
      if (!suggestionKeys.add(key) ||
          related.length > 12 ||
          related.toSet().length != related.length ||
          !keys.containsAll(related) ||
          anchor != null && !related.contains(anchor) ||
          missing.length > 6 ||
          missing.toSet().length != missing.length ||
          !{
            'date',
            'year',
            'time',
            'zone',
            'occurrence',
            'duration',
          }.containsAll(missing)) {
        throw const FormatException('Invalid suggestion references');
      }
      suggestions.add(
        AnalysisSuggestion(
          key: key,
          kind: ActionKind.values.byName(a['kind'] as String),
          title: boundedText(a['title'], 100),
          relatedFactKeys: related,
          anchorFactKey: anchor,
          needsUserInput: missing,
          reason: boundedText(a['reason'], 300),
        ),
      );
    }
    return AnalysisOutput._(
      sourceRevision: expectedRevision,
      documentLabel: boundedText(json['documentLabel'], 100),
      title: boundedText(json['title'], 100),
      summary: boundedText(json['summary'], 300, allowEmpty: true),
      isPartial: expectedPartial,
      analyzedPages: pages,
      facts: facts,
      suggestions: suggestions,
      warnings: rawWarnings.map((w) => boundedText(w, 300)).toList(),
    );
  }
}
